/*
 * This Java source file was auto generated by running 'gradle buildInit --type java-library'
 * by 'U620189' at '17/08/23 16:01' with Gradle 2.14.1
 *
 * @author U620189, @date 17/08/23 16:01
 */
public class Library {
    public boolean someLibraryMethod() {
        return true;
    }
}
